/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EspaceRouteImport } from './routes/espace'
import { Route as ConditionsUtilisationRouteImport } from './routes/conditions-utilisation'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CampRouteImport } from './routes/camp'
import { Route as BibliothequeRouteImport } from './routes/bibliotheque'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ChatConversationIdRouteImport } from './routes/chat.$conversationId'
import { Route as AdminUtilisateursRouteImport } from './routes/admin.utilisateurs'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminBibliothequeRouteImport } from './routes/admin.bibliotheque'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceRoute = EspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsUtilisationRoute = ConditionsUtilisationRouteImport.update({
  id: '/conditions-utilisation',
  path: '/conditions-utilisation',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CampRoute = CampRouteImport.update({
  id: '/camp',
  path: '/camp',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliothequeRoute = BibliothequeRouteImport.update({
  id: '/bibliotheque',
  path: '/bibliotheque',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => ChatRoute,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBibliothequeRoute = AdminBibliothequeRouteImport.update({
  id: '/bibliotheque',
  path: '/bibliotheque',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bibliotheque': typeof BibliothequeRoute
  '/camp': typeof CampRoute
  '/chat': typeof ChatRouteWithChildren
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/espace': typeof EspaceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forum': typeof ForumRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/bibliotheque': typeof AdminBibliothequeRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/camp': typeof CampRoute
  '/chat': typeof ChatRouteWithChildren
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/espace': typeof EspaceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forum': typeof ForumRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/bibliotheque': typeof AdminBibliothequeRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bibliotheque': typeof BibliothequeRoute
  '/camp': typeof CampRoute
  '/chat': typeof ChatRouteWithChildren
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/espace': typeof EspaceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forum': typeof ForumRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/bibliotheque': typeof AdminBibliothequeRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bibliotheque'
    | '/camp'
    | '/chat'
    | '/conditions-utilisation'
    | '/espace'
    | '/forgot-password'
    | '/forum'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/bibliotheque'
    | '/admin/config'
    | '/admin/utilisateurs'
    | '/chat/$conversationId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bibliotheque'
    | '/camp'
    | '/chat'
    | '/conditions-utilisation'
    | '/espace'
    | '/forgot-password'
    | '/forum'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/bibliotheque'
    | '/admin/config'
    | '/admin/utilisateurs'
    | '/chat/$conversationId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bibliotheque'
    | '/camp'
    | '/chat'
    | '/conditions-utilisation'
    | '/espace'
    | '/forgot-password'
    | '/forum'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/bibliotheque'
    | '/admin/config'
    | '/admin/utilisateurs'
    | '/chat/$conversationId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BibliothequeRoute: typeof BibliothequeRoute
  CampRoute: typeof CampRoute
  ChatRoute: typeof ChatRouteWithChildren
  ConditionsUtilisationRoute: typeof ConditionsUtilisationRoute
  EspaceRoute: typeof EspaceRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ForumRoute: typeof ForumRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace': {
      id: '/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof EspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-utilisation': {
      id: '/conditions-utilisation'
      path: '/conditions-utilisation'
      fullPath: '/conditions-utilisation'
      preLoaderRoute: typeof ConditionsUtilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp': {
      id: '/camp'
      path: '/camp'
      fullPath: '/camp'
      preLoaderRoute: typeof CampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bibliotheque': {
      id: '/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof BibliothequeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bibliotheque': {
      id: '/admin/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/admin/bibliotheque'
      preLoaderRoute: typeof AdminBibliothequeRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBibliothequeRoute: typeof AdminBibliothequeRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBibliothequeRoute: AdminBibliothequeRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ChatRouteChildren {
  ChatConversationIdRoute: typeof ChatConversationIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatConversationIdRoute: ChatConversationIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BibliothequeRoute: BibliothequeRoute,
  CampRoute: CampRoute,
  ChatRoute: ChatRouteWithChildren,
  ConditionsUtilisationRoute: ConditionsUtilisationRoute,
  EspaceRoute: EspaceRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ForumRoute: ForumRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
